import random
import hashlib


class StarNamer:
    def __init__(self) -> None:
        self.syllables_start = [
            "Grib",
            "Plok",
            "Zox",
            "Vyr",
            "Kla",
            "Thrum",
            "Xyl",
            "Quor",
            "Bli",
            "Drah",
            "Flux",
            "Jinx",
            "Mox",
            "Nix",
            "Pry",
            "Sphynx",
            "Zeph",
            "Kron",
            "Vex",
            "Tyr",
            "Skol",
            "Drex",
            "Phyx",
            "Zyx",
            "Kresh",
            "Vorn",
            "Thax",
            "Qyth",
            "Ryx",
            "Grax",
            "Blex",
            "Shrex",
            "Vrax",
            "Klyx",
            "Zhur",
            "Branth",
            "Chrox",
            "Syrr",
            "Vuld",
            "Travn",
            "Vrak",
            "Zynt",
            "Phol",
            "Kryv",
            "Glar",
            "Thon",
            "Spyr",
            "Qul",
            "Drom",
            "Blent",
            "Xor",
            "Jurn",
            "Mek",
            "Nost",
            "Prav",
            "Trel",
            "Vyrn",
            "Zel",
            "Krak",
            "Flyn",
            "Grox",
            "Hax",
            "Lyv",
            "Zon",
            "Rhek",
            "Sko",
            "Trox",
            "Vly",
            "Wren",
            "Kyth",
            "Myd",
            "Nax",
            "Manu",
        ]

        self.syllables_end = [
            "tor",
            "nar",
            "xis",
            "wen",
            "zar",
            "kith",
            "lun",
            "rax",
            "morn",
            "vex",
            "cryn",
            "zod",
            "hark",
            "vull",
            "qish",
            "dor",
            "pyx",
            "thon",
            "gax",
            "zyn",
            "kron",
            "phex",
            "wyx",
            "drak",
            "thul",
            "vorn",
            "ryx",
            "gorn",
            "thex",
            "zul",
            "rith",
            "vane",
            "qor",
            "lyth",
            "muth",
            "zurn",
            "tash",
            "vrax",
            "lon",
            "mar",
            "tis",
            "dyn",
            "ver",
            "kas",
            "lyn",
            "rox",
            "marn",
            "vax",
            "cren",
            "zad",
            "herk",
            "vell",
            "qesh",
            "dar",
            "pax",
            "then",
            "zen",
            "kren",
            "phax",
            "wax",
            "drek",
            "thel",
            "varn",
            "garn",
            "thax",
            "zel",
            "nish",
            "vost",
            "manu",
        ]

        self.adjectives = [
            "Silent",
            "Drifting",
            "Iron",
            "Neon",
            "Frozen",
            "Burning",
            "Hidden",
            "Lost",
            "Azure",
            "Crimson",
            "Jagged",
            "Smooth",
            "Echoing",
            "Hollow",
            "Solar",
            "Lunar",
            "Stellar",
            "Void",
            "Ancient",
            "Phantom",
            "Crystal",
            "Shadow",
            "Nebular",
            "Cosmic",
            "Distant",
            "Eternal",
            "Radiant",
            "Mystic",
            "Quantum",
            "Silver",
            "Golden",
            "Darkened",
            "Twisted",
            "Serene",
            "Fractured",
            "Infinite",
            "Shattered",
            "Rusted",
            "Blazing",
            "Celestial",
            "Obsidian",
            "Glimmering",
            "Flickering",
            "Gilded",
            "Piercing",
            "Hallowed",
            "Veiled",
            "Ethereal",
            "Titan",
            "Dormant",
            "Vibrant",
            "Sullen",
            "Primal",
            "Astral",
            "Deep",
            "Pale",
            "Black",
            "White",
            "Red",
            "Blue",
            "Green",
            "Lurid",
            "Faint",
            "Broken",
            "Twin",
            "Dying",
            "New",
            "Old",
            "First",
            "Last",
            "Outer",
            "Inner",
            "High",
            "Low",
            "Wandering",
        ]

        self.nouns = [
            "Dream",
            "Signal",
            "Dust",
            "Shard",
            "Wave",
            "Pulse",
            "Sector",
            "Region",
            "Cluster",
            "Zone",
            "Drift",
            "Gate",
            "Veil",
            "Core",
            "Peak",
            "Abyss",
            "Halo",
            "Tide",
            "Storm",
            "Silence",
            "Nexus",
            "Horizon",
            "Expanse",
            "Void",
            "Nebula",
            "Ember",
            "Echo",
            "Realm",
            "Beacon",
            "Rift",
            "Crown",
            "Threshold",
            "Cascade",
            "Haven",
            "Spire",
            "Dawn",
            "Forge",
            "Sanctum",
            "Monument",
            "Frontier",
            "Citadel",
            "Reach",
            "Labyrinth",
            "Passage",
            "Harbor",
            "Current",
            "Outpost",
            "Anchor",
            "Path",
            "Way",
            "Eye",
            "Heart",
            "Soul",
            "Breath",
            "Spirit",
            "Ghost",
            "Shadow",
            "Light",
            "Dark",
            "Fire",
            "Ice",
            "Cold",
            "Heat",
            "War",
            "Peace",
            "Hope",
            "Fear",
            "Aura",
            "Burst",
            "Cloud",
            "Dance",
            "Edge",
            "Flow",
            "Gaze",
            "Haze",
            "Icon",
            "Jewel",
            "Key",
            "Mirror",
        ]

    def get_seed(self, ra_avg: float, dec_avg: float, mag_avg: float) -> int:
        # Create a unique string based on the segment's stats
        # Rounding ensures slight floating point wobbles don't change the name
        unique_str = f"{ra_avg:.4f}_{dec_avg:.4f}_{mag_avg:.2f}"

        # Turn string into a stable integer seed
        hash_obj = hashlib.md5(unique_str.encode())
        return int(hash_obj.hexdigest(), 16)

    def generate_name(self, ra_avg: float, dec_avg: float, mag_avg: float) -> str:
        # Seed the random generator so this specific spot always gets this name
        seed = self.get_seed(ra_avg, dec_avg, mag_avg)
        rng = random.Random(seed)

        # Decide on a "Style" for this segment
        # 0 = Alien (Grib Plok)
        # 1 = English (Silent Dust)
        # 2 = Hybrid (Neon Zox)
        style = rng.randint(0, 2)

        if style == 0:
            # Alien Style: Two random syllables/words
            part1 = rng.choice(self.syllables_start)

            # 50% chance to be a simple syllable, 50% to be a complex constructed word
            if rng.random() > 0.5:
                part2 = rng.choice(self.syllables_start)
            else:
                part2 = rng.choice(self.syllables_start) + rng.choice(
                    self.syllables_end
                )

            return f"{part1} {part2.capitalize()}"

        if style == 1:
            # English Style: Adjective + Noun
            adj = rng.choice(self.adjectives)
            noun = rng.choice(self.nouns)
            return f"{adj} {noun}"

        # Hybrid Style: English Adjective + Alien Noun OR Alien + English Noun
        if rng.random() > 0.5:
            return f"{rng.choice(self.adjectives)} {rng.choice(self.syllables_start)}"

        return f"{rng.choice(self.syllables_start)} {rng.choice(self.nouns)}"